SELECT P.PRODUCT_ID , 
round( 
    coalesce(SUM(U.UNITS * P.PRICE)/SUM(U.UNITS),0)
    ,2) 
    AS average_price
FROM PRICES AS P left JOIN UNITSSOLD AS U
ON P.PRODUCT_ID = U.PRODUCT_ID AND U.PURCHASE_DATE BETWEEN P.START_DATE AND P.END_DATE
GROUP BY P.PRODUCT_ID;